// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/// @title IVerifier
/// @notice Interface for UltraHonk proof verification (auto-generated by bb from Noir circuit)
interface IVerifier {
    /// @notice Verifies an UltraHonk proof against public inputs
    /// @param proof The serialized proof bytes
    /// @param publicInputs The public inputs to the circuit
    /// @return True if the proof is valid
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external returns (bool);
}
